entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          permanent: true
  https:
    address: ":443"
    asDefault: true
  metrics:
    address: ":8082"

providers:
  docker:
    exposedByDefault: false
    constraints: "Label(`traefik.constraint-label`, `traefik-public`)"
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  le:
    acme:
      # email is set from environment variable
      storage: "/certificates/acme.json"
      tlsChallenge: {}

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

log:
  level: ERROR

# Uncomment to enable the Traefik dashboard
# Caution as this is insecure. Only use for debugging!
# Take a look at the Traefik documentation for more information
# as this can also be enabled with a nice URL and BasicAuth.
#api:
  #dashboard: true
  #insecure: true

accessLog: {}
